DELETE FROM CLIENTES WHERE CIDADE_CLIENTE = 'São Paulo';
UPDATE CLIENTES SET EMAIL = 'jose.silva@email.com' WHERE CPF_CLIENTE = 123456789;
INSERT INTO CLIENTES (CPF_CLIENTE, NOME_CLIENTE, NASC_CLIENTE, STATUS_CLIENTE, RUA_CLIENTE, NUM_CLIENTE, BAIRRO_CLIENTE, CIDADE_CLIENTE, ESTADO_CLIENTE, PAIS_CLIENTE, EMAIL)
VALUES (123456789, 'João Silva', '1985-02-25', 'SIM', 'Rua das Flores', 10, 'Centro', 'São Paulo', 'SP', 'Brasil', 'joao.silva@email.com');
INSERT INTO CLIENTES (CPF_CLIENTE, NOME_CLIENTE, NASC_CLIENTE, STATUS_CLIENTE, RUA_CLIENTE, NUM_CLIENTE, BAIRRO_CLIENTE, CIDADE_CLIENTE, ESTADO_CLIENTE, PAIS_CLIENTE, EMAIL)
VALUES (987654321, 'Ana Costa', '1990-03-10', 'NÃO', 'Avenida Paulista', 100, 'Jardim Paulista', 'São Paulo', 'SP', 'Brasil', 'ana.costa@email.com');
INSERT INTO CLIENTES (CPF_CLIENTE, NOME_CLIENTE, NASC_CLIENTE, STATUS_CLIENTE, RUA_CLIENTE, NUM_CLIENTE, BAIRRO_CLIENTE, CIDADE_CLIENTE, ESTADO_CLIENTE, PAIS_CLIENTE, EMAIL)
VALUES (1122334455, 'Carlos Souza', '1982-05-15', 'SIM', 'Rua do Comércio', 50, 'Centro', 'Belo Horizonte', 'MG', 'Brasil', 'carlos.souza@email.com');

DELETE FROM PRODUTOS WHERE NOME_PROD = 'Camiseta';
UPDATE PRODUTOS SET COR_PROD = 'Azul' WHERE ID_PROD = 104;
INSERT INTO PRODUTOS (ID_PROD, NOME_PROD, DIMENSOES_PROD, VALOR_PROD, DISP_PROD, PROD_FORNC_FORNECEDOR, COR_PROD)
VALUES (101, 'Camiseta', 3, 50, 'SIM', 'Fornecedor A', 'Branca');
INSERT INTO PRODUTOS (ID_PROD, NOME_PROD, DIMENSOES_PROD, VALOR_PROD, DISP_PROD, PROD_FORNC_FORNECEDOR, COR_PROD)
VALUES (102, 'Calça Jeans', 4, 150, 'SIM', 'Fornecedor B', 'Preta');
INSERT INTO PRODUTOS (ID_PROD, NOME_PROD, DIMENSOES_PROD, VALOR_PROD, DISP_PROD, PROD_FORNC_FORNECEDOR, COR_PROD)
VALUES (103, 'Tênis Esportivo', 5, 200, 'NAO', 'Fornecedor C', 'Cinza');


DELETE FROM FORNECEDORES WHERE CONTATO_FORN = 'João Pereira';
UPDATE FORNECEDORES SET CONTATO_FORN = 'Fernanda Oliveira' WHERE ID_FORN = 4;
INSERT INTO FORNECEDORES (ID_FORN, TELEFONE_FORN, CONTATO_FORN, PRODUTO_FORN, DESC_PROD_FORN)
VALUES (1, 999999999, 'João Pereira', 'Camiseta', 'Vende camisetas de algodão');
INSERT INTO FORNECEDORES (ID_FORN, TELEFONE_FORN, CONTATO_FORN, PRODUTO_FORN, DESC_PROD_FORN)
VALUES (2, 888888888, 'Lucas Souza', 'Calça Jeans', 'Vende calças jeans de vários modelos');
INSERT INTO FORNECEDORES (ID_FORN, TELEFONE_FORN, CONTATO_FORN, PRODUTO_FORN, DESC_PROD_FORN)
VALUES (3, 777777777, 'Fernanda Oliveira', 'Tênis Esportivo', 'Vende tênis de diversas marcas');


DELETE FROM ESTOQUE WHERE LOC_PROD_ESTOQUE = 'A2';
UPDATE ESTOQUE SET LOC_PROD_ESTOQUE = 'B3' WHERE ID_ESTOQUE = 4;
INSERT INTO ESTOQUE (ID_ESTOQUE, PROD_ESTOQUE, LOC_PROD_ESTOQUE, QNT_PROD_ESTOQUE, PROD_DISP_ESTOQUE)
VALUES (1, 'Camiseta', 'A1', 100, 80);
INSERT INTO ESTOQUE (ID_ESTOQUE, PROD_ESTOQUE, LOC_PROD_ESTOQUE, QNT_PROD_ESTOQUE, PROD_DISP_ESTOQUE)
VALUES (2, 'Calça Jeans', 'B2', 50, 45);
INSERT INTO ESTOQUE (ID_ESTOQUE, PROD_ESTOQUE, LOC_PROD_ESTOQUE, QNT_PROD_ESTOQUE, PROD_DISP_ESTOQUE)
VALUES (3, 'Tênis Esportivo', 'C3', 30, 20);


DELETE FROM VENDA WHERE PROD_VENDA = 'Tênis Esportivo';
UPDATE VENDA SET DATA_VENDA = '2024-11-10' WHERE ID_VENDA = 4;
INSERT INTO VENDA (ID_VENDA, PROD_VENDA, QNT_PROD_VENDA, PAGAMENTO_VENDA, CLIENTE_VENDA, DATA_VENDA)
VALUES (1, 'Camiseta', 2, 'Dinheiro', 123456789, '2024-11-01');
INSERT INTO VENDA (ID_VENDA, PROD_VENDA, QNT_PROD_VENDA, PAGAMENTO_VENDA, CLIENTE_VENDA, DATA_VENDA)
VALUES (2, 'Calça Jeans', 1, 'Cartão', 987654321, '2024-11-02');
INSERT INTO VENDA (ID_VENDA, PROD_VENDA, QNT_PROD_VENDA, PAGAMENTO_VENDA, CLIENTE_VENDA, DATA_VENDA)
VALUES (3, 'Tênis Esportivo', 3, 'Boleto', 1122334455, '2024-11-03');


DELETE FROM PAGAMENTOS WHERE CLIENTE_PAGAMENTO = 123456789;
UPDATE PAGAMENTOS SET DATA_PAGAMENTO = '2024-11-05' WHERE ID_PAGAMENTO = 4;
INSERT INTO PAGAMENTOS (ID_PAGAMENTO, CLIENTE_PAGAMENTO, DATA_PAGAMENTO, VALOR_TOTAL_PAGAMENTO, STATUS_PAGAMENTO, ID_CLIENTE)
VALUES (1, 123456789, '2024-11-01', 150, 'PAGO', 123456789);
INSERT INTO PAGAMENTOS (ID_PAGAMENTO, CLIENTE_PAGAMENTO, DATA_PAGAMENTO, VALOR_TOTAL_PAGAMENTO, STATUS_PAGAMENTO, ID_CLIENTE)
VALUES (2, 987654321, '2024-11-02', 100, 'PENDENTE', 987654321);
INSERT INTO PAGAMENTOS (ID_PAGAMENTO, CLIENTE_PAGAMENTO, DATA_PAGAMENTO, VALOR_TOTAL_PAGAMENTO, STATUS_PAGAMENTO, ID_CLIENTE)
VALUES (3, 1122334455, '2024-11-03', 200, 'PENDENTE', 1122334455);
