DELETE FROM PASSAGEIROS WHERE PASS_CPF = 123456789;
UPDATE PASSAGEIROS SET PASS_NOME = 'Carlos Almeida' WHERE PASS_CPF = 987654321;
INSERT INTO PASSAGEIROS (PASS_CPF, PASS_NOME, PASS_TELEFONE, PASS_RUA, PASS_BAIRRO, PASS_NUM, PASS_CIDADE, PASS_PAIS) 
VALUES (123456789, 'Maria Oliveira', '21 98765-4321', 'Rua das Flores', 'Centro', 100, 'Rio de Janeiro', 'Brasil');
INSERT INTO PASSAGEIROS (PASS_CPF, PASS_NOME, PASS_TELEFONE, PASS_RUA, PASS_BAIRRO, PASS_NUM, PASS_CIDADE, PASS_PAIS) 
VALUES (987654321, 'João Silva', '11 98888-7777', 'Av. Paulista', 'Bela Vista', 1500, 'São Paulo', 'Brasil');
INSERT INTO PASSAGEIROS (PASS_CPF, PASS_NOME, PASS_TELEFONE, PASS_RUA, PASS_BAIRRO, PASS_NUM, PASS_CIDADE, PASS_PAIS) 
VALUES (112233445, 'Carlos Pereira', '31 99666-5555', 'Rua da Paz', 'Funcionários', 500, 'Belo Horizonte', 'Brasil');

DELETE FROM VOOS WHERE VOO_CODIGO = 123;
UPDATE VOOS SET DATA_HORA_ORIGEM = '2024-11-10 14:30:00' WHERE VOO_CODIGO = 123;
INSERT INTO VOOS (VOO_CODIGO, DATA_HORA_ORIGEM, DATA_DESTINO, HORA_DESTINO, PAIS_DESTINO) 
VALUES (123, '2024-12-01 10:00:00', '2024-12-01', '15:00:00', 'Argentina');
INSERT INTO VOOS (VOO_CODIGO, DATA_HORA_ORIGEM, DATA_DESTINO, HORA_DESTINO, PAIS_DESTINO) 
VALUES (456, '2024-12-15 08:30:00', '2024-12-15', '12:30:00', 'Estados Unidos');
INSERT INTO VOOS (VOO_CODIGO, DATA_HORA_ORIGEM, DATA_DESTINO, HORA_DESTINO, PAIS_DESTINO) 
VALUES (789, '2024-11-20 22:00:00', '2024-11-21', '06:00:00', 'Portugal');

DELETE FROM AEROPORTO WHERE AEROPORTO_COD = 1;
UPDATE AEROPORTO SET AEROPORTO_LOCAL = 'Aeroporto Santos Dumont' WHERE AEROPORTO_COD = 2;
INSERT INTO AEROPORTO (AEROPORTO_COD, AEROPORTO_NOME, AEROPORTO_LOCAL, AEROPORTO_PAIS, AEROPORTO_LONGITUDE, AEROPORTO_LATITUDE) 
VALUES (1, 'Aeroporto Internacional de Guarulhos', 'São Paulo', 'Brasil', -46, -23);
INSERT INTO AEROPORTO (AEROPORTO_COD, AEROPORTO_NOME, AEROPORTO_LOCAL, AEROPORTO_PAIS, AEROPORTO_LONGITUDE, AEROPORTO_LATITUDE) 
VALUES (2, 'Aeroporto Internacional do Rio de Janeiro', 'Rio de Janeiro', 'Brasil', -43, -22);
INSERT INTO AEROPORTO (AEROPORTO_COD, AEROPORTO_NOME, AEROPORTO_LOCAL, AEROPORTO_PAIS, AEROPORTO_LONGITUDE, AEROPORTO_LATITUDE) 
VALUES (3, 'Aeroporto El Prat', 'Barcelona', 'Espanha', 2, 41);

DELETE FROM AERONAVES WHERE AERONAVE_PREFIXO = 1;
UPDATE AERONAVES SET AERONAVE_CAPACIDADE = 250 WHERE AERONAVE_PREFIXO = 2;
INSERT INTO AERONAVES (AERONAVE_PREFIXO, AERONAVE_MODELO, AERONAVE_ANOFAB, AERONAVE_CAPACIDADE, AERONAVE_FABRICANTE) 
VALUES (1, 'Boeing 747', 2005, 350, 'Boeing');
INSERT INTO AERONAVES (AERONAVE_PREFIXO, AERONAVE_MODELO, AERONAVE_ANOFAB, AERONAVE_CAPACIDADE, AERONAVE_FABRICANTE) 
VALUES (2, 'Airbus A380', 2010, 500, 'Airbus');
INSERT INTO AERONAVES (AERONAVE_PREFIXO, AERONAVE_MODELO, AERONAVE_ANOFAB, AERONAVE_CAPACIDADE, AERONAVE_FABRICANTE) 
VALUES (3, 'Embraer E195', 2015, 120, 'Embraer');

DELETE FROM FUNCIONARIOS WHERE FUN_ID = 1;
UPDATE FUNCIONARIOS SET FUN_FUNCAO = 'Co-piloto' WHERE FUN_ID = 2;
INSERT INTO FUNCIONARIOS (FUN_ID, FUN_FUNCAO, FUN_NOME, FUN_DATANASC, FUN_TELEFONE) 
VALUES (1, 'Piloto', 'Ricardo Lima', '1985-05-15', '11 99999-1111');
INSERT INTO FUNCIONARIOS (FUN_ID, FUN_FUNCAO, FUN_NOME, FUN_DATANASC, FUN_TELEFONE) 
VALUES (2, 'Co-piloto', 'Luciana Gomes', '1990-08-20', '21 99777-2222');
INSERT INTO FUNCIONARIOS (FUN_ID, FUN_FUNCAO, FUN_NOME, FUN_DATANASC, FUN_TELEFONE) 
VALUES (3, 'Engenheiro', 'Marcelo Oliveira', '1983-12-10', '31 96666-3333');


DELETE FROM RESERVA WHERE RESERVA_PASS = 123456789;
UPDATE RESERVA SET RESERVA_PASS = 112233445 WHERE VOO_RESERVA_PASS = 789;
INSERT INTO RESERVA (RESERVA_PASS, VOO_RESERVA_PASS) 
VALUES (123456789, 123);
INSERT INTO RESERVA (RESERVA_PASS, VOO_RESERVA_PASS) 
VALUES (987654321, 456);
INSERT INTO RESERVA (RESERVA_PASS, VOO_RESERVA_PASS) 
VALUES (112233445, 789);

DELETE FROM EQUIPES WHERE FUNC_EQUIPE = 1;
UPDATE EQUIPES SET FUNC_EQUIPE = 3 WHERE VOO_EQUIPE = 123;
INSERT INTO EQUIPES (FUNC_EQUIPE, VOO_EQUIPE) 
VALUES (1, 123);
INSERT INTO EQUIPES (FUNC_EQUIPE, VOO_EQUIPE) 
VALUES (2, 456);
INSERT INTO EQUIPES (FUNC_EQUIPE, VOO_EQUIPE) 
VALUES (3, 789);
