DELETE FROM FORNECEDORES
WHERE FORNEC_COD = 5;

DELETE FROM FILIAIS
WHERE FILIAL_COD = 3;

DELETE FROM PRODUTOS
WHERE PROD_COD = 2;

DELETE FROM PEDIDOS
WHERE PED_CODIGO = 2;

DELETE FROM RECEBIMENTOS
WHERE RECEB_PEDIDOS = 1;

DELETE FROM PEDIDOS_PRODUTOS
WHERE PDPR_PEDIDOS = 1 AND PDPR_PRODUTOS = 2;

DELETE FROM FILIAIS_PRODUTOS
WHERE FLPR_FILIAL = 1 AND FLPR_PRODUTOS = 1;

DELETE FROM FORNECEDORES_PRODUTOS
WHERE FRPR_FORNECEDOR = 2 AND FRPR_PRODUTOS = 2;

UPDATE FORNECEDORES_PRODUTOS
SET FRPR_FORNECEDOR = 1
WHERE FRPR_FORNECEDOR = 2 AND FRPR_PRODUTOS = 2;

UPDATE FILIAIS_PRODUTOS
SET FLPR_QUANT = 120
WHERE FLPR_FILIAL = 2 AND FLPR_PRODUTOS = 2;

UPDATE PEDIDOS_PRODUTOS
SET PDPR_QUANT = 25
WHERE PDPR_PEDIDOS = 1 AND PDPR_PRODUTOS = 1;

UPDATE RECEBIMENTOS
SET RECEB_CONDICAO = 'Condição Atualizada' 
WHERE RECEB_PEDIDOS = 1;

UPDATE PEDIDOS
SET PED_STATUS = 'CONCLUÍDO'
WHERE PED_CODIGO = 1;

UPDATE PRODUTOS
SET PROD_NOME = 'Produto Atualizado'
WHERE PROD_COD = 1;

UPDATE FILIAIS
SET FILIAL_NOME = 'Filial Atualizada'
WHERE FILIAL_COD = 2;

UPDATE FORNECEDORES
SET FORNEC_NOME = 'Fornecedor Atualizado' 
WHERE FORNEC_COD = 1;

INSERT INTO FORNECEDORES (FORNEC_COD, FORNEC_NOME, FORNEC_RUA, FORNEC_NUMRUA, FORNEC_BAIRRO, FORNEC_CIDADE, FORNEC_ESTADO, FORNEC_PAIS, FORNEC_CODPOSTAL, FORNEC_TELEFONE, FORNEC_CONTATO) 
VALUES 
(1, '1', 'Av. Central', 100, 'Centro', 'Cidade A', 'ESPIRITO SANTO', 'BRASIL', '12345-666', '33214413', 'FULANO'),
(2, '2', 'Rua 1', 50, 'Centro', 'Cidade B', 'ESPIRITO SANTO', 'BRASIL', '29000-000', '1111111', 'BELTRANO'),
(3, '3', 'Av. das Artes', 75, 'Bairro X', 'Cidade C', 'ESPIRITO SANTO', 'BRASIL', '33333-000', '2222222', 'CICLANO'),
(4, '3', 'Av. Brasil', 200, 'Bairro Y', 'Cidade D', 'ESPIRITO SANTO', 'BRASIL', '44444-000', '3333333', 'CONTRACICLANO'),
(5, '3', 'Rua 2', 10, 'Bairro Z', 'Cidade E', 'ESPIRITO SANTO', 'BRASIL', '55555-000', '44444444', 'TETRAFULANO');

INSERT INTO FILIAIS (FILIAL_COD, FILIAL_NOME, FILIAL_RUA, FILIAL_NUMRUA, FILIAL_BAIRRO, FILIAL_CIDADE, FILIAL_ESTADO, FILIAL_PAIS, FILIAL_CODPOSTAL, FILIAL_CAPACIDADE) 
VALUES 
(1, 'Filial 1', 'Rua A', 150, 'Centro', 'Cidade X', 'ESPIRITO SANTO', 'BRASIL', '12345-777', '1000'),
(2, 'Filial 2', 'Rua B', 200, 'Bairro Y', 'Cidade Y', 'ESPIRITO SANTO', 'BRASIL', '23456-888', '500'),
(3, 'Filial 3', 'Rua C', 50, 'Bairro Z', 'Cidade Z', 'ESPIRITO SANTO', 'BRASIL', '34567-999', '800');

INSERT INTO PRODUTOS (PROD_COD, PROD_NOME, PROD_DESCRICAO, PROD_ESPECTEC, PROD_QUANT, PROD_PRECOUNIT, PROD_UNIDMEDIDA, PROD_ESTOQ_MIN)
VALUES 
(1, 'Produto A', 'Descrição do Produto A', 'Especificação A', 100, 10.50, 'UN', 10),
(2, 'Produto B', 'Descrição do Produto B', 'Especificação B', 200, 25.75, 'UN', 5),
(3, 'Produto C', 'Descrição do Produto C', 'Especificação C', 300, 30.00, 'UN', 20);

INSERT INTO PEDIDOS (PED_CODIGO, PED_DATA, PED_HORA, PED_PREVISAO, PED_STATUS, PED_FORNECEDOR) 
VALUES 
(1, '2024-11-01', '10:00:00', '2024-11-10', 'PENDENTE', 1),
(2, '2024-11-02', '14:00:00', '2024-11-12', 'CONCLUÍDO', 2);

INSERT INTO RECEBIMENTOS (RECEB_DATA, RECEB_HORA, RECEB_QUANT_PROD, RECEB_CONDICAO, RECEB_PEDIDOS)
VALUES
('2024-11-03', '16:00:00', 50, 'Condição A', 1),
('2024-11-04', '09:00:00', 100, 'Condição B', 2);

INSERT INTO PEDIDOS_PRODUTOS (PDPR_PEDIDOS, PDPR_PRODUTOS, PDPR_QUANT)
VALUES 
(1, 1, 10),
(1, 2, 20),
(2, 3, 30);

INSERT INTO FILIAIS_PRODUTOS (FLPR_FILIAL, FLPR_PRODUTOS, FLPR_QUANT)
VALUES 
(1, 1, 50),
(2, 2, 100),
(3, 3, 200);

INSERT INTO FORNECEDORES_PRODUTOS (FRPR_FORNECEDOR, FRPR_PRODUTOS)
VALUES 
(1, 1),
(2, 2),
(3, 3);
