DELETE FROM ALUNO WHERE ALUNO_CPF = 123456789;
UPDATE ALUNO SET ALUNO_NOME = 'Carlos Souza' WHERE ALUNO_CPF = 123456789;

INSERT INTO ALUNO (ALUNO_CPF, ALUNO_NOME, ALUNO_MODALIDADE, ALUNO_TEL, ALUNO_CIDADE, ALUNO_ESTADO, ALUNO_PAIS, ALUNO_RUA, ALUNO_NUM, ALUNO_BAIRRO, EMAIL)
VALUES (123456789, 'João Silva', 'Musculação', '11987654321', 'São Paulo', 'SP', 'Brasil', 'Rua das Flores', '10', 'Jardim Paulista', 'joao.silva@email.com');
INSERT INTO ALUNO (ALUNO_CPF, ALUNO_NOME, ALUNO_MODALIDADE, ALUNO_TEL, ALUNO_CIDADE, ALUNO_ESTADO, ALUNO_PAIS, ALUNO_RUA, ALUNO_NUM, ALUNO_BAIRRO, EMAIL)
VALUES (987654321, 'Maria Oliveira', 'Yoga', '21987654321', 'Rio de Janeiro', 'RJ', 'Brasil', 'Avenida Atlântica', '200', 'Copacabana', 'maria.oliveira@email.com');
INSERT INTO ALUNO (ALUNO_CPF, ALUNO_NOME, ALUNO_MODALIDADE, ALUNO_TEL, ALUNO_CIDADE, ALUNO_ESTADO, ALUNO_PAIS, ALUNO_RUA, ALUNO_NUM, ALUNO_BAIRRO, EMAIL)
VALUES (1122334455, 'Carlos Souza', 'Boxe', '31987654321', 'Belo Horizonte', 'MG', 'Brasil', 'Rua do Comércio', '50', 'Centro', 'carlos.souza@email.com');

DELETE FROM INSTRUTORES WHERE ID_INSTRUTOR = 1;
UPDATE INSTRUTORES SET NOME_INSTRUTOR = 'Roberto Oliveira' WHERE ID_INSTRUTOR = 2;
INSERT INTO INSTRUTORES (ID_INSTRUTOR, NOME_INSTRUTOR, ESPEC_INSTRUTOR, INSTRUTOR_TEL, INSTRUTOR_CIDADE, INSTRUTOR_ESTADO, INSTRUTOR_PAIS, INSTRUTOR_RUA, INSTRUTOR_NUM, INSTRUTOR_BAIRRO, SEXO_INSTRUTOR)
VALUES (1, 'Ana Costa', 'Yoga', '11987654321', 'São Paulo', 'SP', 'Brasil', 'Rua dos Três', '15', 'Vila Mariana', 'F');
INSERT INTO INSTRUTORES (ID_INSTRUTOR, NOME_INSTRUTOR, ESPEC_INSTRUTOR, INSTRUTOR_TEL, INSTRUTOR_CIDADE, INSTRUTOR_ESTADO, INSTRUTOR_PAIS, INSTRUTOR_RUA, INSTRUTOR_NUM, INSTRUTOR_BAIRRO, SEXO_INSTRUTOR)
VALUES (2, 'Carlos Lima', 'Musculação', '21987654321', 'Rio de Janeiro', 'RJ', 'Brasil', 'Avenida Rio Branco', '300', 'Centro', 'M');
INSERT INTO INSTRUTORES (ID_INSTRUTOR, NOME_INSTRUTOR, ESPEC_INSTRUTOR, INSTRUTOR_TEL, INSTRUTOR_CIDADE, INSTRUTOR_ESTADO, INSTRUTOR_PAIS, INSTRUTOR_RUA, INSTRUTOR_NUM, INSTRUTOR_BAIRRO, SEXO_INSTRUTOR)
VALUES (3, 'Fernanda Pereira', 'Pilates', '31987654321', 'Belo Horizonte', 'MG', 'Brasil', 'Rua de Minas', '450', 'Savassi', 'F');

DELETE FROM AULA WHERE ALUNO_AULA = 123456789;
UPDATE AULA SET CAPACIDADE_AULA = 30 WHERE ID_AULA = 101;
INSERT INTO AULA (ID_AULA, CAPACIDADE_AULA, DIA_AULA, INSTRUTOR_AULA, ALUNO_AULA, HORARIO_AULA)
VALUES (101, 20, '2024-11-10', 1, 123456789, '09:00:00');
INSERT INTO AULA (ID_AULA, CAPACIDADE_AULA, DIA_AULA, INSTRUTOR_AULA, ALUNO_AULA, HORARIO_AULA)
VALUES (102, 25, '2024-11-12', 2, 987654321, '14:00:00');
INSERT INTO AULA (ID_AULA, CAPACIDADE_AULA, DIA_AULA, INSTRUTOR_AULA, ALUNO_AULA, HORARIO_AULA)
VALUES (103, 15, '2024-11-14', 3, 1122334455, '18:00:00');

DELETE FROM PAGAMENTOS WHERE STATUR_PAGAMENTO = 'PENDENTE';
UPDATE PAGAMENTOS SET DATA_PAGAMENTO = '2024-11-05 10:00:00' WHERE ID_PAGAMENTO = 4;
INSERT INTO PAGAMENTOS (ID_PAGAMENTO, DATA_PAGAMENTO, VALOR_PAGAMENTO, STATUR_PAGAMENTO, ALUNO_PAGAMENTO)
VALUES (1, '2024-11-01 12:00:00', 100.00, 'PENDENTE', 123456789);
INSERT INTO PAGAMENTOS (ID_PAGAMENTO, DATA_PAGAMENTO, VALOR_PAGAMENTO, STATUR_PAGAMENTO, ALUNO_PAGAMENTO)
VALUES (2, '2024-11-02 13:30:00', 120.00, 'PAGO', 987654321);
INSERT INTO PAGAMENTOS (ID_PAGAMENTO, DATA_PAGAMENTO, VALOR_PAGAMENTO, STATUR_PAGAMENTO, ALUNO_PAGAMENTO)
VALUES (3, '2024-11-03 14:00:00', 130.00, 'PENDENTE', 1122334455);


DELETE FROM PLANO_TREINO WHERE ID_PLANO = 1;
UPDATE PLANO_TREINO SET PLANO_INSTRUTOR = 1 WHERE ID_PLANO = 3;
INSERT INTO PLANO_TREINO (ID_PLANO, PLANO_INSTRUTOR, PLANO_ALUNO)
VALUES (1, 2, 123456789);
INSERT INTO PLANO_TREINO (ID_PLANO, PLANO_INSTRUTOR, PLANO_ALUNO)
VALUES (2, 3, 987654321);
INSERT INTO PLANO_TREINO (ID_PLANO, PLANO_INSTRUTOR, PLANO_ALUNO)
VALUES (3, 1, 1122334455);

DELETE FROM MODALIDADES WHERE ID_MODALIDADE = 1;
UPDATE MODALIDADES SET NOME_MODALIDADE = 'Boxe' WHERE ID_MODALIDADE = 3;
INSERT INTO MODALIDADES (ID_MODALIDADE, NOME_MODALIDADE, INSTRUTOR_MOD)
VALUES (1, 'Yoga', 2);
INSERT INTO MODALIDADES (ID_MODALIDADE, NOME_MODALIDADE, INSTRUTOR_MOD)
VALUES (2, 'Pilates', 3);
INSERT INTO MODALIDADES (ID_MODALIDADE, NOME_MODALIDADE, INSTRUTOR_MOD)
VALUES (3, 'Musculação', 1);
