CREATE SCHEMA CASO4;

USE CASO4;

CREATE TABLE IF NOT EXISTS PAGAMENTOS(
ID_PAGAMENTO INT PRIMARY KEY,
DATA_PAGAMENTO DATETIME,
VALOR_PAGAMENTO DECIMAL(10,2),
STATUR_PAGAMENTO ENUM('PENDENTE','PAGO'),
ALUNO_PAGAMENTO INT,
CONSTRAINT FK_ALUNO FOREIGN KEY (ALUNO_PAGAMENTO)
REFERENCES ALUNO(ALUNO_CPF)
);

CREATE TABLE IF NOT EXISTS AULA(
ID_AULA INT PRIMARY KEY,
CAPACIDADE_AULA INT,
DIA_AULA DATE,
INSTRUTOR_AULA INT,
ALUNO_AULA INT,
CONSTRAINT FK_INSTRUTORES FOREIGN KEY (INSTRUTOR_AULA)
REFERENCES INSTRUTORES(ID_INSTRUTOR),
CONSTRAINT FK_ALUNO FOREIGN KEY (ALUNO_AULA)
REFERENCES ALUNO(ALUNO_CPF)
);

CREATE TABLE IF NOT EXISTS PLANO_TREINO(
ID_PLANO INT PRIMARY KEY,
PLANO_INSTRUTOR INT,
PLANO_ALUNO INT,
CONSTRAINT FK_INSTRUTORES FOREIGN KEY (PLANO_INSTRUTOR)
REFERENCES INSTRUTORES(ID_INSTRUTOR),
CONSTRAINT FK_ALUNO FOREIGN KEY (PLANO_ALUNO)
REFERENCES ALUNO(ALUNO_CPF)
);

CREATE TABLE IF NOT EXISTS PAGAMENTOS(
ID_PAGAMENTO INT PRIMARY KEY,
DATA_PAGAMENTO DATETIME,
VALOR_PAGAMENTO DECIMAL(10,2),
STATUR_PAGAMENTO ENUM('PENDENTE','PAGO'),
ALUNO_PAGAMENTO INT,
CONSTRAINT FK_ALUNO FOREIGN KEY (ALUNO_PAGAMENTO)
REFERENCES ALUNO(ALUNO_CPF)
);

CREATE TABLE IF NOT EXISTS ALUNO(
ALUNO_CPF INT PRIMARY KEY,
ALUNO_NOME VARCHAR(50),
ALUNO_DATANASC DATE,
ALUNO_MODALIDADE TEXT,
ALUNO_TEL VARCHAR(15),
ALUNO_CIDADE VARCHAR(30),
ALUNO_ESTADO VARCHAR(30,
ALUNO_PAIS VARCHAR(30),
ALUNO_RUA VARCHAR(30),
ALUNO_NUM VARCHAR(30),
ALUNO_BAIRRO VARCHAR(30)
);

ALTER TABLE ALUNO ADD EMAIL VARCHAR(30);
ALTER TABLE ALUNO DROP COLUMN ALUNO_DATANASC;

CREATE TABLE IF NOT EXISTS MODALIDADES(
ID_MODALIDADE INT PRIMARY KEY,
NOME_MODALIDADE VARCHAR(30),
INSTRUTOR_MOD VARCHAR(30),
CONSTRAINT FK_INSTRUTORES FOREIGN KEY (INSTRUTOR_MOD)
REFERENCES INSTRUTORES(ID_INSTRUTOR)
);

CREATE TABLE IF NOT EXISTS INSTRUTORES(
ID_INSTRUTOR INT PRIMARY KEY,
NOME_INSTRUTOR VARCHAR(45),
ESPEC_INSTRUTOR VARCHAR(20),
INSTRUTOR_TEL VARCHAR(15),
INSTRUTOR_CIDADE VARCHAR(30),
INSTRUTOR_ESTADO VARCHAR(30,
INSTRUTOR_PAIS VARCHAR(30),
INSTRUTOR_RUA VARCHAR(30),
INSTRUTOR_NUM VARCHAR(30),
INSTRUTOR_BAIRRO VARCHAR(30)
);

ALTER TABLE INSTRUTORES ADD SEXO_INSTRUTOR ENUM('M', 'F');

ALTER TABLE MODALIDADES MODIGY NOME_MODALIDADE VARCHAR(50);

ALTER TABLE PLANO_TREINO CHANGE ID_PLANO ID_PLANO_TREINO INT PRIMARY KEY;

ALTER TABLE AULA ADD HORARIO_AULA TIME;

ALTER TABLE PAGAMENTOS MODIFY VALOR_PAGAMENTO INT;





