CREATE SCHEMA CASO5;

USE CASO5;

CREATE TABLE IF NOT EXISTS ESTOQUE(
ID_ESTOQUE INT PRIMARY KEY,
PROD_ESTOQUE VARCHAR(50) NOT NULL,
LOC_PROD_ESTOQUE VARCHAR(50) NOT NULL,
QNT_PROD_ESTOQUE INT NOT NULL,
PROD_ESTOQUE INT,
END_ESTOQUE INT,
CONSTRAINT FK_PRODUTOS FOREIGN KEY(PROD_ESTOQUE)
REFERENCES PRODUTOS(ID_PROD),
CONSTRAINT FK_ENDERECO FOREIGN KEY(END_ESTOQUE)
REFERENCES ENDERECO(ID_END)
);

CREATE TABLE IF NOT EXISTS PAGAMENTOS(
ID_PAGAMENTO INT PRIMARY KEY,
DATA_PAGAMENTO DATE NOT NULL,
VALOR_PAGAMENTO INT NOT NULL,
STATUS_PAGAMENTO ENUM('PAGO', 'PENDENTE'),
PAG_VENDA INT,
CONSTRAINT FK_VENDA FOREIGN KEY(PAG_VENDA)
REFERENCES VENDA(ID_VENDA)
);

CREATE TABLE IF NOT EXISTS VENDA(
ID_VENDA INT PRIMARY KEY,
PROD_VENDA VARCHAR(30) NOT NULL,
QNT_PROD_VENDA INT NOT NULL,
PAGAMENTO_VENDA VARCHAR(20) NOT NULL,
CLIENTE_VENDA INT,
CONSTRAINT FK_CLIENTE FOREIGN KEY(CLIENTE_VENDA)
REFERENCES CLIENTES(CPF_CLIENTE)
);

CREATE TABLE IF NOT EXISTS CLIENTES(
CPF_CLIENTE INT PRIMARY KEY,
NOME_CLIENTE VARCHAR(45) NOT NULL,
NASC_CLIENTE DATE,
STATUS_CLIENTE ENUM('SIM', 'NÃO'),
END_CLIENTE INT,
PAG_CLIENTE INT,
CONSTRAINT FK_ENDERECO FOREIGN KEY (END_CLIENTE)
REFERENCES ENDERECO(ID_END),
CONSTRAINT FK_PAGAMENTOS FOREIGN KEY(PAG_CLIENTE)
REFERENCES PAGAMENTOS(ID_PAGAMENTO)
);

ALTER TABLE CLIENTES ADD EMAIL VARCHAR(50);
ALTER TABLE CLIENTES DROP COLUMN NASC_CLIENTE;

CREATE TABLE IF NOT EXISTS ENDERECO(
ID_END INT PRIMARY KEY,
RUA_END VARCHAR(50) NOT NULL,
NUM_END INT NOT NULL,
BAIRRO_END VARCHAR(50) NOT NULL,
CIDADE_END VARCHAR(50) NOT NULL,
ESTADO_END VARCHAR(50) NOT NULL,
PAIS_END VARCHAR(40) NOT NULL
);

ALTER TABLE ENDERECO MODIFY PAIS_END VARCHAR(50);

CREATE TABLE IF NOT EXISTS FORNECEDORES(
ID_FORN INT PRIMARY KEY,
TELEFONE_FORN INT NOT NULL,
CONTATO_FORN VARCHAR(50) NOT NULL,
PRODUTO_FORN VARCHAR(30) NOT NULL,
DESCPROD_FORN VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS PRODUTOS(
ID_PROD INT PRIMARY KEY,
NOME_PROD VARCHAR(70) NOT NULL,
DIMENSOES_PROD INT NOT NULL,
VALOR_PROD INT NOT NULL,
DISP_PROD ENUM('SIM', 'NAO'),
PROD_FORN INT,
CONSTRAINT FK_FORNECEDOR FOREIGN KEY(PROD_FORN)
REFERENCES FORNECEDORES(ID_FORN)
);

ALTER TABLE PRODUTOS ADD COR_PROD VARCHAR(20);

ALTER TABLE FORNECEDORES CHANGE DESCPROD_FORN DESC_PROD_FORN VARCHAR(100) NOT NULL;

ALTER TABLE VENDA ADD DATA_VENDA DATE;

ALTER TABLE PAGAMENTOS CHANGE VALOR_PAGAMENTO VALOR_TOTAL_PAGAMENTO INT NOT NULL;

