DROP SCHEMA CASO3;
CREATE SCHEMA CASO3;

USE CASO3;

CREATE TABLE IF NOT EXISTS TIPO_TEL(
ID_TEL INT PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS TELEFONES(
NUM_TELEFONE INT PRIMARY KEY,
TIPO_TELEFONE INT,
CONSTRAINT FK_TIPO_TEL FOREIGN KEY(TIPO_TELEFONE)
REFERENCES TIPO_TEL(ID_TEL)
);

CREATE TABLE IF NOT EXISTS TIPO_END(
ID_TIPO INT PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS ENDERECO(
ID_END INT PRIMARY KEY,
RUA_END VARCHAR(50) NOT NULL,
BAIRRO_END VARCHAR(50) NOT NULL,
NUM_END INT NOT NULL,
CIDADE_END VARCHAR(50) NOT NULL,
ESTADO_END VARCHAR(50) NOT NULL,
TIPO_ENDERECO INT,
CONSTRAINT FK_TIPO_END FOREIGN KEY(TIPO_ENDERECO)
REFERENCES TIPO_END(ID_TIPO)
);

CREATE TABLE IF NOT EXISTS FORNECEDORES(
CNPJ_FORN INT PRIMARY KEY,
RAZAO_SOCIAL_FORN VARCHAR(50),
TELEFONE_FORNECEDOR INT,
ENDERECO_FORNECEDOR INT,
CONSTRAINT FK_TELEFONE FOREIGN KEY(TELEFONE_FORNECEDOR) 
REFERENCES TELEFONES(NUM_TELEFONE),
CONSTRAINT FK_ENDERECO FOREIGN KEY(ENDERECO_FORNECEDOR)
REFERENCES ENDERECO(ID_END)
);

CREATE TABLE IF NOT EXISTS TIPOCOMPONENTE(
ID_TC INT PRIMARY KEY,
NOME_TC VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS COMPONENTES(
ID_COMP INT PRIMARY KEY,
NOME_COMP VARCHAR(50) NOT NULL,
QNT_ESTOQUE_COMP INT NOT NULL,
PREÇO_COMP INT,
COMP_FORNECEDOR INT,
TIPO_COMP INT,
FORN_COMP INT,
CONSTRAINT FK_FORNECEDORES FOREIGN KEY (COMP_FORNECEDOR) 
REFERENCES FORNECEDORES(CNPJ_FORN),
CONSTRAINT FK_TIPOCOMPONENTE FOREIGN KEY(TIPO_COMP) 
REFERENCES TIPOCOMPONENTE(ID_TC),
CONSTRAINT FK_COMPONENTES FOREIGN KEY(FORN_COMP)
REFERENCES COMPONENTES(ID_COMP)
);

CREATE TABLE IF NOT EXISTS EMPRESAS(
CNPJ_EMPRESA INT PRIMARY KEY,
CONTATO_EMPRESA VARCHAR(70) NOT NULL,
TELEFONE_EMPRESA INT,
ENDERECO_EMPRESA INT,
CONSTRAINT FK_TELEFONEEMP FOREIGN KEY(TELEFONE_EMPRESA) 
REFERENCES TELEFONES(NUM_TELEFONE),
CONSTRAINT FK_ENDERECOEMP FOREIGN KEY(ENDERECO_EMPRESA)
REFERENCES ENDERECO(ID_END)
);

CREATE TABLE IF NOT EXISTS ENCOMENDAS(
ID_ENC INT PRIMARY KEY,
DATA_INCLUSAO_ENC DATE NOT NULL,
VALOR_TOTAL_ENC INT NOT NULL,
VALOR_DESCONTO_ENC INT NOT NULL,
VALOR_LIQUIDO_ENC INT NOT NULL,
FORMA_PAGAMENTO_ENC VARCHAR(30) NOT NULL,
ENC_PRODUTOS TEXT
);

CREATE TABLE IF NOT EXISTS RE(
ID_RE INT PRIMARY KEY,
QNT_NECE_RE INT NOT NULL,
UNID_RE INT NOT NULL,
TEMP_USO_RE TIME NOT NULL
);

ALTER TABLE RE ADD HR_MAO_DE_OBRA_RE TIME;

CREATE TABLE IF NOT EXISTS RM(
ID_RM INT PRIMARY KEY,
DATA_RM DATE NOT NULL,
DESC_RM VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS RS(
ID_RS INT PRIMARY KEY,
QNT_RS INT NOT NULL,
DATA_NESC_RS DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS PRODUTOS(
ID_PROD INT PRIMARY KEY,
NOME_PROD VARCHAR(70) NOT NULL,
COR_PROD VARCHAR(20) NOT NULL,
DIMENSOES_PROD INT NOT NULL,
PESO_PROD INT,
VALOR_PROD INT NOT NULL,
TEMP_FABRICACAO_PROD TIME,
HORAS_MAO_DE_OBRA_PROD TIME,
PROD_ENCOMENDAS INT,
COMP_ENCOMENDAS INT,
RE_PROD INT,
RS_PROD INT,
CONSTRAINT FK_ENCOMENDAS FOREIGN KEY(PROD_ENCOMENDAS)
REFERENCES ENCOMENDAS(ID_ENC),
CONSTRAINT FK_COMPONENTESPROD FOREIGN KEY(COMP_ENCOMENDAS)
REFERENCES COMPONENTES(ID_COMP),
CONSTRAINT FK_REPROD FOREIGN KEY(RE_PROD)
REFERENCES RE(ID_RE),
CONSTRAINT FK_RSPROD FOREIGN KEY(RS_PROD)
REFERENCES RS(ID_RS)
);

CREATE TABLE IF NOT EXISTS EMPREGADOS(
ID_EMPREGADO INT PRIMARY KEY,
NOME_EMPREGADO VARCHAR(70) NOT NULL,
CARGO_EMPREGADO VARCHAR(50) NOT NULL,
SALARIO_EMPREGADO INT NOT NULL,
QUALIFICACOES_EMPREGADO VARCHAR(50) NOT NULL,
TELEFONE_EMPREGADO INT,
END_EMPREGADO INT,
EMPREGADO_PROD INT,
CONSTRAINT FK_TELEFONEEMPG FOREIGN KEY(TELEFONE_EMPREGADO) 
REFERENCES TELEFONES(NUM_TELEFONE),
CONSTRAINT FK_ENDERECOEMPG FOREIGN KEY(END_EMPREGADO)
REFERENCES ENDERECO(ID_END),
CONSTRAINT FK_PRODUTOSEMPG FOREIGN KEY(EMPREGADO_PROD)
REFERENCES PRODUTOS(ID_PROD)
);

CREATE TABLE IF NOT EXISTS CLIENTES(
ID_CLIENTE INT PRIMARY KEY,
CNPJ_CLIENTE INT NOT NULL,
RAZSOC_CLIENTE VARCHAR(50) NOT NULL,
RAMO_CLIENTE VARCHAR(30) NOT NULL,
TELEFONE_CLIENTE INT,
END_CLIENTE INT,
TIPO_TELEFONE INT,
CLIENTE_ENC INT,
CONSTRAINT FK_TELEFONECLI FOREIGN KEY(TELEFONE_CLIENTE) 
REFERENCES TELEFONES(NUM_TELEFONE),
CONSTRAINT FK_ENDERECOCLI FOREIGN KEY(END_CLIENTE)
REFERENCES ENDERECO(ID_END),
CONSTRAINT FK_TIPO_TELCLI FOREIGN KEY(TIPO_TELEFONE)
REFERENCES TIPO_TEL(ID_TEL),
CONSTRAINT FK_ENCOMENDASCLI FOREIGN KEY(CLIENTE_ENC)
REFERENCES ENCOMENDAS(ID_ENC)
);

ALTER TABLE CLIENTES ADD DATA_CADAST_CLIENTE DATE;

ALTER TABLE CLIENTES MODIFY RAMO_CLIENTE VARCHAR(50);

ALTER TABLE CLIENTES ADD EMAIL VARCHAR(50);

ALTER TABLE CLIENTES DROP COLUMN EMAIL;

ALTER TABLE EMPREGADOS ADD DATA_EMISSAO_EMPREGADO DATE;

ALTER TABLE EMPRESAS ADD RAZAO_SOCIAL_EMPRESA VARCHAR(50);

ALTER TABLE FORNECEDORES ADD CONTATO_FORN VARCHAR(70);

ALTER TABLE ENCOMENDAS ADD QUANT_PARCELAS_ENC INT;

ALTER TABLE PRODUTOS ADD DESENHO_PROD VARCHAR(30);

ALTER TABLE COMPONENTES ADD UNIDADE_COMP INT;

CREATE TABLE IF NOT EXISTS MAQUINAS(
ID_MAQUINA INT PRIMARY KEY,
TEMPO_VIDA_MAQUINA TIME NOT NULL,
DATA_COMPRA_MAQUINA DATE NOT NULL,
RM_MAQUINAS INT,
CONSTRAINT FK_RM FOREIGN KEY(RM_MAQUINAS)
REFERENCES RM(ID_RM)
);

ALTER TABLE MAQUINAS ADD DATA_FIM_GARANTIA_MAQUINA DATE;

ALTER TABLE TIPO_TEL ADD NOME_TEL VARCHAR(30);

ALTER TABLE ENDERECO ADD PAIS_END VARCHAR(50);
