CREATE SCHEMA CASO4;

USE CASO4;

CREATE TABLE IF NOT EXISTS ALUNO(
ALUNO_CPF INT PRIMARY KEY,
ALUNO_NOME VARCHAR(50),
ALUNO_DATANASC DATE,
ALUNO_RUA VARCHAR(50),
ALUNO_BAIRRO VARCHAR(30),
ALUNO_NUM INT,
ALUNO_CIDADE VARCHAR(50),
ALUNO_ESTADO VARCHAR(50),
ALUNO_PAIS VARCHAR(30)
);

CREATE TABLE IF NOT EXISTS INSTRUTORES(
ID_INSTRUTOR INT PRIMARY KEY,
NOME_INSTRUTOR VARCHAR(45),
ESPEC_INSTRUTOR VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS MODALIDADES(
ID_MODALIDADE INT PRIMARY KEY,
NOME_MODALIDADE VARCHAR(30),
CONSTRAINT FK_INSTRUTORES FOREIGN KEY (INSTRUTOR_MOD)
REFERENCES INSTRUTORES(ID_INSTRUTOR)
);

CREATE TABLE IF NOT EXISTS PLANO_TREINO(
ID_PLANO INT PRIMARY KEY,
CONSTRAINT FK_INSTRUTORES FOREIGN KEY (PLANO_INSTRUTOR)
REFERENCES INSTRUTORES(ID_INSTRUTOR),
CONSTRAINT FK_ALUNO FOREIGN KEY (PLANO_ALUNO)
REFERENCES ALUNO(ALUNO_CPF)
);

CREATE TABLE IF NOT EXISTS AULA(
ID_AULA INT PRIMARY KEY,
CAPACIDADE_AULA INT,
HORARIO_DIA_AULA DATETIME,
CONSTRAINT FK_INSTRUTORES FOREIGN KEY (INSTRUTOR_AULA)
REFERENCES INSTRUTORES(ID_INSTRUTOR),
CONSTRAINT FK_ALUNO FOREIGN KEY (ALUNO_AULA)
REFERENCES ALUNO(ALUNO_CPF)
);

CREATE TABLE IF NOT EXISTS PAGAMENTOS(
ID_PAGAMENTO INT PRIMARY KEY,
DATA_PAGAMENTO DATETIME,
VALOR_PAGAMENTO DECIMAL(3,2),
STATUR_PAGAMENTO ENUM('PENDENTE','PAGO'),
CONSTRAINT FK_ALUNO FOREIGN KEY (ALUNO_PAGAMENTO)
REFERENCES ALUNO(ALUNO_CPF)
);







