CREATE SCHEMA CASO2;

USE CASO2;

CREATE TABLE IF NOT EXISTS EQUIPES(
FUNC_EQUIPE VARCHAR(45),
VOO_EQUIPE INT,
constraint FK_FUNCIONARIOS_VOO foreign key (FUNC_EQUIPE)
REFERENCES FUNCIONARIOS(FUNC_ID),
CONSTRAINT FK_VOOS_EQUIPE FOREIGN KEY (VOO_EQUIPE)
REFERENCES VOOS(VOO_CODIGO)
);

CREATE TABLE IF NOT EXISTS RESERVA(
RESERVA_PASS INT,
VOO_RESERVA_PASS INT,
CONSTRAINT FK_PASSAGEIROS FOREIGN KEY (RESERVA_PASS)
REFERENCES PASSAGEIROS(PASS_CPF),
CONSTRAINT FK_VOOS FOREIGN KEY (VOO_RESERVA_PASS)
REFERENCES VOOS(VOO_COD)
);

CREATE TABLE IF NOT EXISTS PASSAGEIROS(
PASS_CPF INT PRIMARY KEY,
PASS_NOME VARCHAR(50),
PASS_TELEFONE VARCHAR(20),
PASS_RUA VARCHAR(30),
PASS_BAIRRO VARCHAR(30),
PASS_NUM INT,
PASS_CIDADE VARCHAR(30),
PASS_PAIS VARCHAR(30),
PASS_EMAIL varchar(50)
);

ALTER TABLE PASSAGEIROS DROP COLUMN PASS_EMAIL;

CREATE TABLE IF NOT EXISTS VOOS(
VOO_CODIGO INT PRIMARY KEY,
DATA_HORA_ORIGEM datetime,
DATA_DESTINO DATE,
HORA_DESTINO TIME
);

ALTER TABLE VOOS ADD PAIS_DESTINO VARCHAR(30);

CREATE TABLE IF NOT EXISTS AEROPORTO(
AEROPORTO_COD INT PRIMARY KEY,
AEROPORTO_NOME VARCHAR(50),
AEROPORTO_LOCAL VARCHAR(50),
AEROPORTO_PAIS VARCHAR(30),
AEROPORTO_LONGITUDE DECIMAL(30,30),
AEROPORTO_LATITUDE DECIMAL(30,30)
);

ALTER TABLE AEROPORTO MODIFY AEROPORTO_LONGITUDE INT;
ALTER TABLE AEROPORTO MODIFY AEROPORTO_LATITUDE INT;

CREATE TABLE IF NOT EXISTS AERONAVES(
AERONAVE_PREFIXO INT PRIMARY KEY,
AERONAVE_MODELO VARCHAR(30),
AERONAVE_ANOFAB YEAR,
AERONAVE_CAPACIDADE INT,
AERONAVE_FABRICANTE VARCHAR(40)
);

ALTER TABLE AERONAVES ADD AERONAVE_EMPRESA VARCHAR(30);

CREATE TABLE IF NOT EXISTS FUNCIONARIOS(
FUNC_ID INT PRIMARY KEY,
FUN_FUNCAO VARCHAR(30),
FUNC_NOME VARCHAR(50),
FUNC_DATANASC DATE,
FUNC_TELEFONE VARCHAR(30)
);

ALTER TABLE FUNCIONARIOS MODIFY FUNC_NOME VARCHAR(70);


